services:
  mysql:
    image: mysql:8.0
    container_name: goga-database
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: goga
      MYSQL_USER: goga
      MYSQL_PASSWORD: goga_password
    ports:
      - "3307:3306"
    volumes:
      - goga-mysql-data:/var/lib/mysql

volumes:
  goga-mysql-data:
