// <auto-generated />
using System;
using Goga.Backend.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Goga.Backend.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260927120744_AddNews")]
    partial class AddNews
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Goga.Backend.Domain.Courses.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("courses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Name = "Основы backend-разработки"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            Name = "Информатика"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            Name = "Основы программирования"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            Name = "Алгоритмы и структуры данных"
                        });
                });

            modelBuilder.Entity("Goga.Backend.Domain.Courses.Section", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("PdfPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("sections", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            CourseId = new Guid("10000000-0000-0000-0000-000000000001"),
                            Name = "Введение",
                            PdfPath = "/pdf/courses/backend/introduction.pdf"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            CourseId = new Guid("10000000-0000-0000-0000-000000000001"),
                            Name = "Архитектура приложения",
                            PdfPath = "/pdf/courses/backend/architecture.pdf"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000003"),
                            CourseId = new Guid("10000000-0000-0000-0000-000000000002"),
                            Name = "Информация и данные",
                            PdfPath = "/pdf/courses/informatics/data.pdf"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000004"),
                            CourseId = new Guid("10000000-0000-0000-0000-000000000002"),
                            Name = "Компьютерные системы",
                            PdfPath = "/pdf/courses/informatics/systems.pdf"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000005"),
                            CourseId = new Guid("10000000-0000-0000-0000-000000000003"),
                            Name = "Переменные и типы данных",
                            PdfPath = "/pdf/courses/programming/types.pdf"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000006"),
                            CourseId = new Guid("10000000-0000-0000-0000-000000000003"),
                            Name = "Функции и классы",
                            PdfPath = "/pdf/courses/programming/functions.pdf"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000007"),
                            CourseId = new Guid("10000000-0000-0000-0000-000000000004"),
                            Name = "Сложность алгоритмов",
                            PdfPath = "/pdf/courses/algorithms/complexity.pdf"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000008"),
                            CourseId = new Guid("10000000-0000-0000-0000-000000000004"),
                            Name = "Графы и деревья",
                            PdfPath = "/pdf/courses/algorithms/graphs.pdf"
                        });
                });

            modelBuilder.Entity("Goga.Backend.Domain.Courses.UserCourse", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("EnrolledAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("UserId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("user_courses", (string)null);
                });

            modelBuilder.Entity("Goga.Backend.Domain.News.News", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("news", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000001"),
                            Description = "В приложении доступны курсы, лекции и расписание занятий.",
                            Title = "Добро пожаловать в Goga"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000002"),
                            Description = "Изучайте информатику, программирование, алгоритмы и backend-разработку.",
                            Title = "Добавлены новые курсы"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000003"),
                            Description = "Актуальное расписание доступно в разделе «Расписание».",
                            Title = "Проверьте расписание"
                        });
                });

            modelBuilder.Entity("Goga.Backend.Domain.Timetables.ScheduleEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Auditorium")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Building")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<int>("Format")
                        .HasColumnType("int");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Lecturer")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("WeekParity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Group", "DayOfWeek", "WeekParity");

                    b.ToTable("schedule_entries", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000001"),
                            Auditorium = "ауд. 101",
                            Building = "Корпус 1",
                            DayOfWeek = 0,
                            Format = 0,
                            Group = "ИС-101",
                            Lecturer = "Иванов И.И.",
                            Number = 1,
                            Subject = "Информатика",
                            Type = 0,
                            WeekParity = 0
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000002"),
                            Auditorium = "ауд. 101",
                            Building = "Корпус 1",
                            DayOfWeek = 0,
                            Format = 0,
                            Group = "ИС-101",
                            Lecturer = "Иванов И.И.",
                            Number = 1,
                            Subject = "Информатика",
                            Type = 0,
                            WeekParity = 1
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000003"),
                            Auditorium = "ауд. 102",
                            Building = "Корпус 1",
                            DayOfWeek = 1,
                            Format = 0,
                            Group = "ИС-101",
                            Lecturer = "Иванов И.И.",
                            Number = 2,
                            Subject = "Математический анализ",
                            Type = 0,
                            WeekParity = 0
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000004"),
                            Auditorium = "ауд. 102",
                            Building = "Корпус 1",
                            DayOfWeek = 1,
                            Format = 0,
                            Group = "ИС-101",
                            Lecturer = "Иванов И.И.",
                            Number = 2,
                            Subject = "Математический анализ",
                            Type = 0,
                            WeekParity = 1
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000005"),
                            Auditorium = "ауд. 103",
                            Building = "Корпус 1",
                            DayOfWeek = 2,
                            Format = 0,
                            Group = "ИС-101",
                            Lecturer = "Иванов И.И.",
                            Number = 3,
                            Subject = "Программирование",
                            Type = 1,
                            WeekParity = 0
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000006"),
                            Auditorium = "ауд. 103",
                            Building = "Корпус 1",
                            DayOfWeek = 2,
                            Format = 0,
                            Group = "ИС-101",
                            Lecturer = "Иванов И.И.",
                            Number = 3,
                            Subject = "Программирование",
                            Type = 1,
                            WeekParity = 1
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000007"),
                            Auditorium = "ауд. 104",
                            Building = "Корпус 1",
                            DayOfWeek = 3,
                            Format = 0,
                            Group = "ИС-101",
                            Lecturer = "Иванов И.И.",
                            Number = 1,
                            Subject = "Базы данных",
                            Type = 0,
                            WeekParity = 0
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000008"),
                            Auditorium = "ауд. 104",
                            Building = "Корпус 1",
                            DayOfWeek = 3,
                            Format = 0,
                            Group = "ИС-101",
                            Lecturer = "Иванов И.И.",
                            Number = 1,
                            Subject = "Базы данных",
                            Type = 0,
                            WeekParity = 1
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000009"),
                            Auditorium = "ауд. 105",
                            Building = "Корпус 1",
                            DayOfWeek = 4,
                            Format = 0,
                            Group = "ИС-101",
                            Lecturer = "Иванов И.И.",
                            Number = 2,
                            Subject = "Алгоритмы",
                            Type = 1,
                            WeekParity = 0
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000010"),
                            Auditorium = "ауд. 105",
                            Building = "Корпус 1",
                            DayOfWeek = 4,
                            Format = 0,
                            Group = "ИС-101",
                            Lecturer = "Иванов И.И.",
                            Number = 2,
                            Subject = "Алгоритмы",
                            Type = 1,
                            WeekParity = 1
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000011"),
                            Auditorium = "ауд. 106",
                            Building = "Корпус 1",
                            DayOfWeek = 5,
                            Format = 1,
                            Group = "ИС-101",
                            Lecturer = "Иванов И.И.",
                            Number = 3,
                            Subject = "Архитектура ПО",
                            Type = 0,
                            WeekParity = 0
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000012"),
                            Auditorium = "ауд. 106",
                            Building = "Корпус 1",
                            DayOfWeek = 5,
                            Format = 1,
                            Group = "ИС-101",
                            Lecturer = "Иванов И.И.",
                            Number = 3,
                            Subject = "Архитектура ПО",
                            Type = 0,
                            WeekParity = 1
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000013"),
                            Auditorium = "ауд. 107",
                            Building = "Корпус 1",
                            DayOfWeek = 6,
                            Format = 0,
                            Group = "ИС-101",
                            Lecturer = "Иванов И.И.",
                            Number = 1,
                            Subject = "Проектная работа",
                            Type = 0,
                            WeekParity = 0
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000014"),
                            Auditorium = "ауд. 107",
                            Building = "Корпус 1",
                            DayOfWeek = 6,
                            Format = 0,
                            Group = "ИС-101",
                            Lecturer = "Иванов И.И.",
                            Number = 1,
                            Subject = "Проектная работа",
                            Type = 0,
                            WeekParity = 1
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000015"),
                            Auditorium = "ауд. 101",
                            Building = "Корпус 2",
                            DayOfWeek = 0,
                            Format = 0,
                            Group = "БПИ-101",
                            Lecturer = "Петров П.П.",
                            Number = 1,
                            Subject = "Информатика",
                            Type = 0,
                            WeekParity = 0
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000016"),
                            Auditorium = "ауд. 101",
                            Building = "Корпус 2",
                            DayOfWeek = 0,
                            Format = 0,
                            Group = "БПИ-101",
                            Lecturer = "Петров П.П.",
                            Number = 1,
                            Subject = "Информатика",
                            Type = 0,
                            WeekParity = 1
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000017"),
                            Auditorium = "ауд. 102",
                            Building = "Корпус 2",
                            DayOfWeek = 1,
                            Format = 0,
                            Group = "БПИ-101",
                            Lecturer = "Петров П.П.",
                            Number = 2,
                            Subject = "Математический анализ",
                            Type = 0,
                            WeekParity = 0
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000018"),
                            Auditorium = "ауд. 102",
                            Building = "Корпус 2",
                            DayOfWeek = 1,
                            Format = 0,
                            Group = "БПИ-101",
                            Lecturer = "Петров П.П.",
                            Number = 2,
                            Subject = "Математический анализ",
                            Type = 0,
                            WeekParity = 1
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000019"),
                            Auditorium = "ауд. 103",
                            Building = "Корпус 2",
                            DayOfWeek = 2,
                            Format = 0,
                            Group = "БПИ-101",
                            Lecturer = "Петров П.П.",
                            Number = 3,
                            Subject = "Программирование",
                            Type = 1,
                            WeekParity = 0
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000020"),
                            Auditorium = "ауд. 103",
                            Building = "Корпус 2",
                            DayOfWeek = 2,
                            Format = 0,
                            Group = "БПИ-101",
                            Lecturer = "Петров П.П.",
                            Number = 3,
                            Subject = "Программирование",
                            Type = 1,
                            WeekParity = 1
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000021"),
                            Auditorium = "ауд. 104",
                            Building = "Корпус 2",
                            DayOfWeek = 3,
                            Format = 0,
                            Group = "БПИ-101",
                            Lecturer = "Петров П.П.",
                            Number = 1,
                            Subject = "Базы данных",
                            Type = 0,
                            WeekParity = 0
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000022"),
                            Auditorium = "ауд. 104",
                            Building = "Корпус 2",
                            DayOfWeek = 3,
                            Format = 0,
                            Group = "БПИ-101",
                            Lecturer = "Петров П.П.",
                            Number = 1,
                            Subject = "Базы данных",
                            Type = 0,
                            WeekParity = 1
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000023"),
                            Auditorium = "ауд. 105",
                            Building = "Корпус 2",
                            DayOfWeek = 4,
                            Format = 0,
                            Group = "БПИ-101",
                            Lecturer = "Петров П.П.",
                            Number = 2,
                            Subject = "Алгоритмы",
                            Type = 1,
                            WeekParity = 0
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000024"),
                            Auditorium = "ауд. 105",
                            Building = "Корпус 2",
                            DayOfWeek = 4,
                            Format = 0,
                            Group = "БПИ-101",
                            Lecturer = "Петров П.П.",
                            Number = 2,
                            Subject = "Алгоритмы",
                            Type = 1,
                            WeekParity = 1
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000025"),
                            Auditorium = "ауд. 106",
                            Building = "Корпус 2",
                            DayOfWeek = 5,
                            Format = 1,
                            Group = "БПИ-101",
                            Lecturer = "Петров П.П.",
                            Number = 3,
                            Subject = "Архитектура ПО",
                            Type = 0,
                            WeekParity = 0
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000026"),
                            Auditorium = "ауд. 106",
                            Building = "Корпус 2",
                            DayOfWeek = 5,
                            Format = 1,
                            Group = "БПИ-101",
                            Lecturer = "Петров П.П.",
                            Number = 3,
                            Subject = "Архитектура ПО",
                            Type = 0,
                            WeekParity = 1
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000027"),
                            Auditorium = "ауд. 107",
                            Building = "Корпус 2",
                            DayOfWeek = 6,
                            Format = 0,
                            Group = "БПИ-101",
                            Lecturer = "Петров П.П.",
                            Number = 1,
                            Subject = "Проектная работа",
                            Type = 0,
                            WeekParity = 0
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000028"),
                            Auditorium = "ауд. 107",
                            Building = "Корпус 2",
                            DayOfWeek = 6,
                            Format = 0,
                            Group = "БПИ-101",
                            Lecturer = "Петров П.П.",
                            Number = 1,
                            Subject = "Проектная работа",
                            Type = 0,
                            WeekParity = 1
                        });
                });

            modelBuilder.Entity("Goga.Backend.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("varchar(320)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("IdentityServerSubject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IdentityServerSubject")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Goga.Backend.Domain.Courses.Section", b =>
                {
                    b.HasOne("Goga.Backend.Domain.Courses.Course", "Course")
                        .WithMany("Sections")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Goga.Backend.Domain.Courses.UserCourse", b =>
                {
                    b.HasOne("Goga.Backend.Domain.Courses.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Goga.Backend.Domain.Users.User", "User")
                        .WithMany("Courses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Goga.Backend.Domain.Courses.Course", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("Sections");
                });

            modelBuilder.Entity("Goga.Backend.Domain.Users.User", b =>
                {
                    b.Navigation("Courses");
                });
#pragma warning restore 612, 618
        }
    }
}
